language: node_js
node_js:
  - '5.11'
  - '4.4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm install
  - cd na-backend && npm install
  - cd ../na-client && npm install
before_script:
  - cd ..
script:
  - cd na-backend && npm run coverage
  - cd ../na-client && npm run coverage
after_success:
  - cat coverage/lcov.info > ../lcov.info
  - cd ../na-backend && cat coverage/lcov.info >> ../lcov.info
  - cd ..
  - npm run send-coverage
